### ISSUE TITLE
Facing issues while using cmdstanr

### ISSUE THREAD

**Issue by baldwaprateek** [stan-dev/cmdstanr#322]
I am trying to use cmdstanr for running a stan model as below:

file <- file.path(cmdstan_path(), "examples", "bernoulli", "bernoulli.stan")
mod <- cmdstan_model(file)
data_list <- list(N = 10, y = c(0,1,0,0,0,0,0,0,0,1))
fit <- mod$sample(
  data = data_list,
  seed = 123,
  num_chains = 2,
  num_cores = 2
)

I am facing the below error:
Compiling Stan program...
INFO: Could not find files for the given pattern(s).
 
Error: An error occured during compilation! See the message above for more information.

Need help to resolve this.

**Comment by baldwaprateek** [comment]
Hi,

Thank you for replying.

R version - 4.0.3
R tools - rtools40

Yes, I am running these commands on Windows

**Comment by rok-cesnovar** [comment]
In that case run: 

```
processx::run(
    "pacman",
    args = c("-Syu", "mingw-w64-x86_64-make","--noconfirm"),
    wd = file.path(Sys.getenv("RTOOLS40_HOME"), "usr", "bin"),
    error_on_status = TRUE
)
write('PATH="${RTOOLS40_HOME}\\usr\\bin;${RTOOLS40_HOME}\\mingw64\\bin;${PATH}"', file = "~/.Renviron", append = TRUE)
```
and restart R or Rstudio if you are using that. Then reinstall cmdstan using `install_cmdstanr(overwrite = TRUE)`. You should be good to go then.

**Comment by baldwaprateek** [comment]
I tried running above commands and then restarted R to install cmdstan. However, I encountered below error:

INFO: Could not find files for the given pattern(s).
cp bin/windows-stanc bin/stanc.exe
g++ -std=c++1y -m64 -D_REENTRANT -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs -Wno-int-in-bool-context -Wno-attributes -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2019_U8/include -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.7 -I stan/lib/stan_math/lib/boost_1.72.0 -I stan/lib/stan_math/lib/sundials_5.2.0/include  -D_USE_MATH_DEFINES  -DBOOST_DISABLE_ASSERTS      -c -fvisibility=hidden -o bin/cmdstan/stansummary.o src/cmdstan/stansummary.cpp
cd stan/lib/stan_math/lib/boost_1.72.0; ./bootstrap.bat gcc
Building Boost.Build engine

Generating Boost.Build configuration in project-config.jam for gcc...

Bootstrapping is done. To build, run:

    .\b2

To adjust configuration, edit 'project-config.jam'.
Further information:

    - Command line help:
    .\b2 --help
     
    - Getting started guide: 
    http://boost.org/more/getting_started/windows.html
     
    - Boost.Build documentation:
    http://www.boost.org/build/

cd stan/lib/stan_math/lib/boost_1.72.0; ./b2  address-model=64 --visibility=hidden --with-program_options cxxstd=11 variant=release link=static
Performing configuration checks

    - default address-model    : 64-bit
    - default architecture     : x86

Building the Boost C++ Libraries.



Component configuration:

    - atomic                   : not building
    - chrono                   : not building
    - container                : not building
    - context                  : not building
    - contract                 : not building
    - coroutine                : not building
    - date_time                : not building
    - exception                : not building
    - fiber                    : not building
    - filesystem               : not building
    - graph                    : not building
    - graph_parallel           : not building
    - headers                  : not building
    - iostreams                : not building
    - locale                   : not building
    - log                      : not building
    - math                     : not building
    - mpi                      : not building
    - program_options          : building
    - python                   : not building
    - random                   : not building
    - regex                    : not building
    - serialization            : not building
    - stacktrace               : not building
    - system                   : not building
    - test                     : not building
    - thread                   : not building
    - timer                    : not building
    - type_erasure             : not building
    - wave                     : not building

...patience...
g++ -std=c++1y -m64 -D_REENTRANT -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs -Wno-int-in-bool-context -Wno-attributes -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2019_U8/include -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.7 -I stan/lib/stan_math/lib/boost_1.72.0 -I stan/lib/stan_math/lib/sundials_5.2.0/include  -D_USE_MATH_DEFINES  -DBOOST_DISABLE_ASSERTS      -c -fvisibility=hidden -o bin/cmdstan/print.o src/cmdstan/print.cpp
...found 1073 targets...
...updating 48 targets...
boost-install.generate-cmake-config-version- bin.v2\tools\boost_install\BoostConfigVersion.cmake
common.copy C:\Users\baldw\OneDrive\Documents\.cmdstanr\cmdstan-2.24.1\stan\lib\stan_math\lib\boost_1.72.0\stage\lib\cmake\BoostDetectToolset-1.72.0.cmake
C:\Users\baldw\OneDrive\Documents\.cmdstanr\cmdstan-2.24.1\stan\lib\stan_math\lib\boost_1.72.0\tools\boost_install\BoostDetectToolset.cmake
        1 file(s) copied.
boost-install.generate-cmake-config- bin.v2\libs\program_options\build\stage\boost_program_options-config.cmake
boost-install.generate-cmake-config- bin.v2\libs\headers\build\stage\boost_headers-config.cmake
boost-install.generate-cmake-config-version- bin.v2\libs\headers\build\stage\boost_headers-config-version.cmake
boost-install.generate-cmake-config-version- bin.v2\libs\program_options\build\stage\boost_program_options-config-version.cmake
common.copy C:\Users\baldw\OneDrive\Documents\.cmdstanr\cmdstan-2.24.1\stan\lib\stan_math\lib\boost_1.72.0\stage\lib\cmake\boost_program_options-1.72.0\boost_program_options-config-version.cmake
bin.v2\libs\program_options\build\stage\boost_program_options-config-version.cmake
        1 file(s) copied.
common.copy C:\Users\baldw\OneDrive\Documents\.cmdstanr\cmdstan-2.24.1\stan\lib\stan_math\lib\boost_1.72.0\stage\lib\cmake\boost_program_options-1.72.0\boost_program_options-config.cmake
bin.v2\libs\program_options\build\stage\boost_program_options-config.cmake
        1 file(s) copied.
common.copy C:\Users\baldw\OneDrive\Documents\.cmdstanr\cmdstan-2.24.1\stan\lib\stan_math\lib\boost_1.72.0\stage\lib\cmake\boost_headers-1.72.0\boost_headers-config.cmake
bin.v2\libs\headers\build\stage\boost_headers-config.cmake
        1 file(s) copied.
common.copy C:\Users\baldw\OneDrive\Documents\.cmdstanr\cmdstan-2.24.1\stan\lib\stan_math\lib\boost_1.72.0\stage\lib\cmake\Boost-1.72.0\BoostConfig.cmake
C:\Users\baldw\OneDrive\Documents\.cmdstanr\cmdstan-2.24.1\stan\lib\stan_math\lib\boost_1.72.0\tools\boost_install\BoostConfig.cmake
        1 file(s) copied.
gcc.compile.c++ bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\config_file.o
gcc.compile.c++ bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\options_description.o
gcc.compile.c++ bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\cmdline.o
gcc.compile.c++ bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\positional_options.o
gcc.compile.c++ bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\parsers.o
gcc.compile.c++ bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\utf8_codecvt_facet.o
gcc.compile.c++ bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\convert.o
gcc.compile.c++ bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\variables_map.o
common.copy C:\Users\baldw\OneDrive\Documents\.cmdstanr\cmdstan-2.24.1\stan\lib\stan_math\lib\boost_1.72.0\stage\lib\cmake\boost_headers-1.72.0\boost_headers-config-version.cmake
bin.v2\libs\headers\build\stage\boost_headers-config-version.cmake
        1 file(s) copied.
common.copy C:\Users\baldw\OneDrive\Documents\.cmdstanr\cmdstan-2.24.1\stan\lib\stan_math\lib\boost_1.72.0\stage\lib\cmake\Boost-1.72.0\BoostConfigVersion.cmake
bin.v2\tools\boost_install\BoostConfigVersion.cmake
        1 file(s) copied.
gcc.compile.c++ bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\winmain.o
gcc.compile.c++ bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\value_semantic.o
gcc.compile.c++ bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\split.o
gcc.archive bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\libboost_program_options-mgw83-mt-x64-1_72.a
boost-install.generate-cmake-variant- bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\libboost_program_options-variant-mgw83-mt-x64-1_72-static.cmake
common.copy C:\Users\baldw\OneDrive\Documents\.cmdstanr\cmdstan-2.24.1\stan\lib\stan_math\lib\boost_1.72.0\stage\lib\libboost_program_options-mgw83-mt-x64-1_72.a
bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\libboost_program_options-mgw83-mt-x64-1_72.a
        1 file(s) copied.

    type "C:\Users\baldw\AppData\Local\Temp\jam2584296e.000" > "bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\libboost_program_options-variant-mgw83-mt-x64-1_72-static.cmake"

...failed text-action bin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden\libboost_program_options-variant-mgw83-mt-x64-1_72-static.cmake...
...skipped <pC:\Users\baldw\OneDrive\Documents\.cmdstanr\cmdstan-2.24.1\stan\lib\stan_math\lib\boost_1.72.0\stage\lib\cmake\boost_program_options-1.72.0>libboost_program_options-variant-mgw83-mt-x64-1_72-static.cmake for lack of <pbin.v2\libs\program_options\build\gcc-8.3.0\release\cxxstd-11-iso\link-static\threading-multi\visibility-hidden>libboost_program_options-variant-mgw83-mt-x64-1_72-static.cmake...
...failed updating 1 target...
...skipped 1 target...
...updated 46 targets...
mingw32-make.exe: *** [make/command:36: stan/lib/stan_math/lib/boost_1.72.0/stage/lib/libboost_program_options*.a] Error 1
mingw32-make.exe: *** Waiting for unfinished jobs....

Warning message:
There was a problem during installation. See the error message(s) above.

**Comment by rok-cesnovar** [comment]
Ok, but you should be able to now run: 

```
file <- file.path(cmdstan_path(), "examples", "bernoulli", "bernoulli.stan")
mod <- cmdstan_model(file)
data_list <- list(N = 10, y = c(0,1,0,0,0,0,0,0,0,1))
fit <- mod$sample(
data = data_list,
seed = 123,
num_chains = 2,
num_cores = 2
)
```
The first compilation might take awhile but should then be working.

**Comment by rok-cesnovar** [comment]
Actually, you can now install the latest verson of cmdstanr with

devtools::install_github("stan-dev/cmdstanr")

and the try installing again. Please report if this works. Thanks!

**Comment by baldwaprateek** [comment]
Hi,

Thanks for replying.

Now it is giving me some different error as below:

_Compiling the C++ model
Running MCMC with 1 chain, with 2 thread(s) per chain...

Warning: Chain 1 finished unexpectedly!

Error in rstan::read_stan_csv(out$output_files()) : 
  csvfiles does not contain any CSV file name
In addition: Warning message:
No chains finished successfully. Unable to retrieve the fit._

**Comment by rok-cesnovar** [comment]
So this is another model you are running now? Given that you are using threading? Can you share the model and data?

**Comment by baldwaprateek** [comment]
Yes, now I am trying new model with my actual requirements. 
Due to data security issues, it won't be possible for me to share data details here however, let me share the model setup as below (just masked actual variables)

my_prior <- c(prior(normal(0,100),class='b',nlpar='Int')+
                prior(beta(6,112),class='b',nlpar='A',lb=0,ub=1)+
                prior(beta(0.24,24),class='b',nlpar='B',lb=0,ub=1)+
                prior(beta(2.15,70),class='b',nlpar='C',lb=0,ub=1)+
                prior(beta(2.15,70),class='b',nlpar='D',lb=0,ub=1)+
                prior(beta(23,202),class='b',nlpar='E',lb=0,ub=1)+
                prior(beta(23,202),class='b',nlpar='F',lb=0,ub=1)+
                prior(beta(32,232),class='b',nlpar='G',lb=0,ub=1)+
                prior(beta(32,232),class='b',nlpar='H',lb=0,ub=1)+
                prior(normal(0,100),class='b',nlpar='I')+
                prior(normal(0,100),class='b',nlpar='J')+
                prior(normal(0,100),class='b',nlpar='K')+
                prior(normal(0,100),class='b',nlpar='L')+
                prior(normal(0,100),class='b',nlpar='M')+
                prior(normal(0,100),class='b',nlpar='N')+
                prior(normal(0,100),class='b',nlpar='O'))
library(future)
plan(multiprocess,workers=5)
start.time <- Sys.time()
model <- brm_multiple(bf(out ~ Int
                         +A1+B1+C1+D1+E1+F1+G1+H1
                         +I1+J1+K1+L1+M1+N1+O1
                         ,nl=TRUE)+
                        lf(Int ~ 1)+
                        lf(A1 ~ 0+A)+
                        lf(B1 ~ 0+B)+
                        lf(C1 ~ 0+C)+
                        lf(D1 ~ 0+D)+
                        lf(E1 ~ 0+E)+
                        lf(F1 ~ 0+F)+
                        lf(G1 ~ 0+G)+
                        lf(H1 ~ 0+H)+
                        lf(I1 ~ 0+I)+
                        lf(J1~0+J)+
                        lf(K1~0+K)+
                        lf(L1~0+L)+
                        lf(M1~0+M)+
                        lf(N1~0+N)+
                        lf(O1~0+O),
                      data = df_split,
                      family = bernoulli("logit"),
                      prior = my_prior,warmup = 1000,chains = 5,cores=5,
                      seed=12345,iter=2000,silent  = FALSE,
                      backend = "cmdstanr", threads = threading(2))

**Comment by rok-cesnovar** [comment]
There was an issue with `brms` parallel code generation that was fixed recently. Can you try installing brms from Github and trying again?

**Comment by baldwaprateek** [comment]
Hi,

I tried re-installing BRMS 2.14.2 from Github as suggested and still facing the same error.

Warning: Chain 1 finished unexpectedly!

Error in rstan::read_stan_csv(out$output_files()) : 
  csvfiles does not contain any CSV file name
In addition: Warning message:
No chains finished successfully. Unable to retrieve the fit.

**Comment by rok-cesnovar** [comment]
This turned out to be a brms thing, that @paul-buerkner already fixed (if you encounter this, use the Github version of brms). Closing.
