### ISSUE TITLE
More informative error messages on system call error

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstanr#69]
I was running a model that was built with a different version of CmdStan than I intended and so it wasn't taking an extra argument I'd hacked into my cmdstanr. I was getting this error:

```
experimental=1 is either mistyped or misplaced.
Failed to parse arguments, terminating Stan
 Error in processx::run(command = runset$command(), args = runset$command_args()[[chain]],  : 
  System command error 
```

This error wasn't super helpful.

If we printed stdout/stderr + the command that was executed I think it would be much more useful for figuring out what's going wrong.

**Comment by jgabry** [comment]
Thanks. Yeah I think there are several places where we run system commands where this would be helpful.

**Comment by jgabry** [comment]
not identical, but related to #60

**Comment by jgabry** [comment]
Should be fixed by #61

**Comment by bbbales2** [comment]
I don't think this is quite fixed. I had an issue today where a chain failed:

```
Running MCMC with 1 chain(s) on 1 core(s)...

Running ./accel_splines 'id=1' random 'seed=942518684' 'init=0.25' data 'file=/tmp/RtmpL91l1l/standata-f361fd69e0d.json' output \
  'file=/tmp/RtmpL91l1l/accel_splines-stan-sample-1-f364f0ba1be.csv' \
  'diagnostic_file=/tmp/RtmpL91l1l/accel_splines-stan-sample-diagnostic-1-f3637ff39c9.csv' 'method=sample' 'num_samples=0' 'num_warmup=100' \
  'save_warmup=1' 'algorithm=hmc' 'metric=dense_e' 'engine=nuts' adapt 'experimental=1' 'which_adaptation=0' 'delta=0.99' 'engaged=1' \
  'init_buffer=100' 'term_buffer=0' 'window=0'
Warning: Chain 1 finished unexpectedly!
```

And there's no info there to figure out what happened.

What turned out to be the issue was I'd moved my cmdstan install and that messed up tbb linking. I think stdout/stderr should print in these situations.

**Comment by jgabry** [comment]
Ok thanks for reopening!

**Comment by jgabry** [comment]
@bbbales2 This may have been fixed by @rok-cesnovar as part of #85. If you try your example again is the output better?

**Comment by bbbales2** [comment]
More information! If there's an error, can we just report all stdout/stderr?

I'm still getting the same error if I:
1. Build a model
2. Change the name of the cmdstan folder
3. Update my cmdstan path and model path
4. Run the model again

The error I see in R is:
```
Running ./diamonds 'id=1' random 'seed=258747578' data 'file=/home/bbales2/warmup/cmdstan2/diamonds.dat' output \
  'file=/tmp/RtmpacRmUZ/diamonds-stan-sample-1-219c70041b92.csv' 'method=sample' 'save_warmup=0' 'algorithm=hmc' \
  'engine=nuts' adapt 'experimental=1' 'engaged=1'
Warning: Chain 1 finished unexpectedly!
```

The error I see on the terminal is:
```
bbales2@frog:~/warmup/cmdstan2$ ./diamonds 'id=2' random 'seed=1449438057' data 'file=/home/bbales2/warmup/cmdstan2/diamonds.dat' output \
>   'file=/tmp/RtmpacRmUZ/diamonds-stan-sample-2-219c51688e35.csv' 'method=sample' 'save_warmup=0' 'algorithm=hmc' \
>   'engine=nuts' adapt 'experimental=1' 'engaged=1'
./diamonds: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory
```

This is the type of output I get when I replace the binary with something totally wacko (I just moved the model header file in the place of the binary and marked it as an executable):
```
Running ./diamonds 'id=1' random 'seed=292465321' data 'file=/home/bbales2/warmup/cmdstan/diamonds.dat' output \
  'file=/tmp/RtmpacRmUZ/diamonds-stan-sample-1-219ce98af3d.csv' 'method=sample' 'save_warmup=0' 'algorithm=hmc' 'engine=nuts' \
  adapt 'experimental=1' 'engaged=1'
Warning: Chain 1 finished unexpectedly!
```

This is what happens on the command line if you run this:
```
bbales2@frog:~/warmup/cmdstan$ ./diamonds
./diamonds: line 1: //: Is a directory
./diamonds: line 5: namespace: command not found
./diamonds: line 7: using: command not found
./diamonds: line 8: using: command not found
./diamonds: line 9: using: command not found
./diamonds: line 10: using: command not found
./diamonds: line 11: using: command not found
./diamonds: line 12: using: command not found
./diamonds: line 13: using: command not found
./diamonds: line 14: using: command not found
./diamonds: line 16: static: command not found
./diamonds: line 18: syntax error near unexpected token `('
./diamonds: line 18: `stan::io::program_reader prog_reader__() {'
```

**Comment by jgabry** [comment]
Fixed by #94
